require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - db/migrate/**
  SuggestExtensions: false

Performance:
  enabled: true

Style:
  Exclude:
    - db/schema.rb
Layout:
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/LineLength:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Metrics:
  Enabled: false
