require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - db/migrate/**

Performance:
  enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb

Rails/HelperInstanceVariable:
  Enabled: false

Rails/TimeZone:
  Enabled: false
