require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - db/migrate/**
  SuggestExtensions: false

Performance:
  enabled: true
Performance/RedundantBlockCall:
  Enabled: false

Style:
  Exclude:
    - db/schema.rb
Layout:
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/LineLength:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Metrics:
  Enabled: false
