require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1

Performance:
  enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb

Rails/HelperInstanceVariable:
  Enabled: false

Rails/TimeZone:
  Enabled: false
