blank_issues_enabled: false
contact_links:
  - name: Problems/questions/bugs about Git program
    url: https://git-scm.com/community
    about: Start a discussion on the community mailing list.

  - name: Problems about Git for Windows program
    url: https://github.com/git-for-windows/git/issues
    about: Report problems with the Git for Windows program.

  - name: Git documentation (man/help pages)
    url: https://git-scm.com/community
    about: Git documentation (anything with a URL starting with https://git-scm.com/docs).

  - name: Pro Git 2 book content
    url: https://github.com/progit/progit2/issues
    about: Report problems with the ProGit 2 book content.
