name: CI/PR
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: ruby setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true

    - name: rails setup
      run: bundle exec rake db:create db:schema:load

    - name: rubocop
      run: bundle exec rubocop -P

    - name: rspec
      run: bundle exec rspec
